#!/bin/zsh

gstatus=`git status --porcelain nb/*`

if [ ${#gstatus} -ne 0 ]
then

    commit_message="Automated commit $gstatus"
    git add nb/*
    git commit -m $commit_message
	git pull
    git push

fi